# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？
   print('list(a): ', list(a))
   print('tolist(): ', a.tolist)
   
2. 請試著在程式中印出以下三個 NdArray 的屬性？
  （屬性：ndim、shape、size、dtype、itemsize、length、type）
   a = np.random.randint(10, size = 6)
   b = np.random.randint(10, size = (3,4))
   c = np.random.randint(10, size = (2,3,2)
  
3. [簡答題] 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？
   print('type(a): ', type(a))
   print('a.dtype: ', a.dtype)


## 作業

1. [簡答題] 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？
   print('list(a): ', list(a))
   print('tolist(): ', a.tolist)

In [14]:
#list(a)只會把第一層的元素轉換成list，多層的話只有第一層會轉
#tolist()多層的型態轉換
import numpy as np
a = np.arange(6).reshape(2,3)

print('list(a): ', list(a))
print('tolist(): ', a.tolist())

list(a):  [array([0, 1, 2]), array([3, 4, 5])]
tolist():  [[0, 1, 2], [3, 4, 5]]


2. 請試著在程式中印出以下三個 NdArray 的屬性？
   （屬性：ndim、shape、size、dtype、itemsize、length、type）
   a = np.random.randint(10, size = 6)
   b = np.random.randint(10, size = (3,4))
   c = np.random.randint(10, size = (2,3,2)

In [19]:
import numpy as np

a = np.random.randint(10, size = 6)
print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

[8 9 2 2 5 2]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [21]:
import numpy as np

b = np.random.randint(10, size = (3,4))
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

[[9 1 7 2]
 [1 1 0 1]
 [6 8 6 2]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [25]:
import numpy as np

c = np.random.randint(10, size = (2,3,2))
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[[[2 2]
  [8 3]
  [1 4]]

 [[5 5]
  [0 4]
  [4 2]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


3. [簡答題] 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？
   print('type(a): ', type(a))
   print('a.dtype: ', a.dtype)

In [35]:
#type() 返回資料結構型別（list、dict、numpy.ndarray 等）
#dtype() 返回資料元素的資料型別（int、float等）

import numpy as np

a = np.random.randint(10, size = 6)

print('type(a):', type(a))
print('a.dtype:', a.dtype)

type(a): <class 'numpy.ndarray'>
a.dtype: int32
