# D02_Numpy 陣列中不同的資料型態

## Study Summary

NumPy 提供了一個同類型元素的多維容器型態，稱為是數組或陣列。
陣列的全名是 N-dimensional Array，習慣簡寫為 NdArray 或 Array

In [6]:
#印出陣列
import numpy as np
a = np.arange(10).reshape(2,5)
print(a)
a #用Jupyter印出陣列

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

陣列常用屬性

In [3]:
print(a.dtype)  #陣列中的資料型態
print(a.itemsize) #陣列中每個元素占用的空間

int32
4


numpy中的型態判斷
is 和 == 差別

In [19]:
#is相對==比較嚴格
print(a.dtype == 'int32')
print(a.dtype == np.int32)
print(a.dtype is np.dtype('int32')) #僅np.type可用 is
print(a.dtype == np.dtype('int32'))

True
True
True
True


Difference between type() and dtype

In [88]:
import numpy as np
a = np.arange(10).reshape(2,5)
b = np.array([10, 20, 30, 40])
c = np.arange(3)
d = np.random.rand(2,3)

print (type(a))
print (type(b))
print (type(c))
print (type(d))
print ("=============")
print (a.dtype)
print (b.dtype)
print (c.dtype)
print (d.dtype)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
int32
int32
int32
float64
