# [作業目標]


1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？
2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

## 作業

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

In [14]:
# np.zeros會產生真正的0
# np.empty會產生近似於0的陣列
import numpy as np

a = np.zeros((2, 3))
print(a)

print("================")

b = np.empty((6, 3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]
[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [9.34609111e-307 1.33511018e-306 1.33511969e-306]
 [6.23037996e-307 6.23053954e-307 9.34609790e-307]
 [8.45593934e-307 9.34600963e-307 1.86921143e-306]
 [6.23061763e-307 2.22522053e-306 1.11261095e-306]
 [1.24610383e-306 1.33511290e-306 8.34445562e-308]]


2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。

In [24]:
#用round做四捨五入

b = np.random.rand(2, 3) * 10 
print(b)
print(b.round())   #第一種寫法
print(np.round(b)) #第二種寫法

[[2.81370955 3.67190596 1.04778317]
 [2.78369574 8.70507343 6.51990106]]
[[3. 4. 1.]
 [3. 9. 7.]]
[[3. 4. 1.]
 [3. 9. 7.]]


3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

In [9]:
#限制整數的範圍介於 m - n 之間
m = 20
n = 40

b = np.random.rand(2, 3) * 10 * (n - m) 
print(b)
print("==========")
print(b.round())

[[ 62.18453174   3.92873058  14.53631858]
 [133.69545113  99.99303502 118.48788191]]
[[ 62.   4.  15.]
 [134. 100. 118.]]


In [5]:
import numpy as np
m = 20
n = 40
c = np.random.randint(20,40,6)
print(c)

[23 32 33 20 20 22]
