1. [簡答題] 請問下列程式碼，運算結果分別為何？
2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？
3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？
4. 廣播（Broadcast）運算的特性
5. 用容器運算(append)，達到陣列運算結果
6. 用flat運算多維陣列

1. [簡答題] 請問下列程式碼，運算結果分別為何？

In [35]:
import numpy as np
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
print('1:', a+a)
print('2:', a+b)
print('3:', a+c)
print('4:', a+d)
print('5:', a+e)

1: [ 40  60  80 100]
2: [21 32 43 54]
3: [21 31 41 51]
4: [21 31 41 51]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

2. 如何在不用迴圈的情況下計算 (A+B)*(-A/2) ？那用迴圈怎麼做？

In [13]:
a = np.array( [2,4,6,8] )
b = np.array( [1,2,3,4] )
c= a+b
print(c)

d=-a/2
print(c*d)

[ 3  6  9 12]
[ -3. -12. -27. -48.]


In [18]:
a=np.ones(3)*2
b=np.ones(3)*1
print((a+b) * (-a/2))

[-3. -3. -3.]


3. 請問如何計算「1x6 的單位矩陣」和「6x1 的單位矩陣」的內積和外積？

In [25]:
a=np.ones((1,6))
b=np.ones((6,1))
print(a * b)
print(a @ b)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[6.]]


4. 廣播（Broadcast）運算的特性

In [19]:
import numpy as np
a=np.array([10,20,30,40,50])
print(a-5)
print(a/10)
print(a+1)

[ 5 15 25 35 45]
[1. 2. 3. 4. 5.]
[11 21 31 41 51]


5. python的容器運算(append)，同樣可以達到陣列運算的結果

In [18]:
a=[10,20,30,40,50]
b=[]
for i in a:
    b.append(i+1)
print(b)

data=np.array([[1,1],[3,4],[7,8]])
new_row=np.array([[1,1]])
print(data+new_row)

[11, 21, 31, 41, 51]
[[2 2]
 [4 5]
 [8 9]]


6. 用flat運算多維陣列

In [27]:
import numpy as np
a = np.array([20,30,40,50])+1
print(a)

b = np.arange(10).reshape(2,5)+10
print(b)

c = np.arange(6).reshape(3,2)
for row in c.flat:
        row = row+10
        print(row)

[21 31 41 51]
[[10 11 12 13 14]
 [15 16 17 18 19]]
10
11
12
13
14
15
