# Study Summary

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？
3. 陣列中的比較運算，廣播

## Summary

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數

In [ ]:
import numpy as np

In [6]:
a=np.arange(11)
print(a)
a[(3<=a) & (a<=6)] *=-1
print(a)


[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -3 -4 -5 -6  7  8  9 10]


2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？

In [8]:
A=np.random.rand(2,6)
print(A[A>0.5].size)

7


3. 陣列中的比較運算，廣播

In [5]:
a = np.array([20,30,40,50])
b = np.arange(4)
print(a>b)
print(a<b)
print(a==b)
print(a!=b)

[ True  True  True  True]
[False False False False]
[False False False False]
[ True  True  True  True]


In [8]:
thriller=['niya','jay','wang','lin']
print(thriller[2])
thriller=[11,22,33,44,55]
print(thriller[2])

wang
33


In [12]:
#遮罩特性背後的強大之處
a=np.arange(10)
print(a)
print(a>6) #利用布林值作為篩選的條件：遮罩 Mask
print(a[a>6])

[0 1 2 3 4 5 6 7 8 9]
[False False False False False False False  True  True  True]
[7 8 9]


In [10]:
a = np.array([10,20,30])
print (a>20)
print(a[ [True, False, True] ])
print( [a>20] )

[False False  True]
[10 30]
[array([False, False,  True])]


In [18]:
a = np.arange( 10 )
b = []
for i in a:
    if i > 6 :
        b.append(i)
print(b)

[7, 8, 9]


# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？

## 作業

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。

In [10]:
a=np.arange(11)
print(a)
a[(a>=3) & (a<=6) ] *= -1
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -3 -4 -5 -6  7  8  9 10]


2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？

In [1]:
a= np.random.rand(2,6)
print(a[a> 0.5])
print(a[a> 0.5].size)

[0.66685679 0.97395146 0.53657485 0.74778422 0.63962405]
5
[[0.49818499 0.12177453 0.66685679 0.10464625 0.14970882 0.97395146]
 [0.53657485 0.74778422 0.38530053 0.49685975 0.63962405 0.4200787 ]]
