# D06_Numpy 中常見的陣列方法與函式


## [作業內容]

1. 從陣列中查找最小元素，最大元素，百分位標準差和方差
2. [簡答題] 請問下列這三種方法有什麼不同？
   print(a.sum())
   print(np.sum(a))
   print(sum(a)) 
3. reshape and resize差別
4. 將多維形狀的陣列轉換成一維(攤平)
5. 請對一個 5x5 的隨機矩陣作正規化的操作
6. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1
7. 用sort排序

1. 從陣列中查找最小元素，最大元素，百分位標準差和方差

In [14]:
import numpy as np
a = np.arange(6)
print(a)

print(a.sum())
print(a.min())
print(a.max())

b = np.arange(12).reshape(2,6)
print(b)
print(b.sum())
print(b.sum(axis=0)) #上下加起來
print(b.sum(axis=1)) #橫向加起來

[0 1 2 3 4 5]
15
0
5
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
66
[ 6  8 10 12 14 16]
[15 51]
[0 1 2 3 4 5]


2. [簡答題] 請問下列這三種方法有什麼不同？
   print(a.sum())
   print(np.sum(a))
   print(sum(a)) 

In [45]:
import numpy as np
a = np.arange(10)
print(a.sum())
print(np.sum(a))
print(sum(a))

45
45
45


3. reshape and resize差別

In [25]:
import numpy as np
a = np.arange(12)   #reshape保留原本的樣子
print(a.reshape(3,4))
print(a)

b = np.arange(12)   #resize樣子被改變
print(b.resize(3,4))
print(b)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
None
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


4. 將多維形狀的陣列轉換成一維(攤平)

In [27]:
import numpy as np 

a = np.arange(6).reshape((3, 2))
print(a.ravel() )
print(a.flatten())
print(a.flat)
print(list(a.flat))

[0 1 2 3 4 5]
[0 1 2 3 4 5]
[0, 1, 2, 3, 4, 5]


5. 請對一個 5x5 的隨機矩陣作正規化的操作

In [40]:
import numpy as np
a = np.arange(25).reshape(5,5)
print(a)
b = np.random.random((5,5))
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[0.26515128 0.15576206 0.22392561 0.63791785 0.21892515]
 [0.42714701 0.55177408 0.9507938  0.06851178 0.45738707]
 [0.72011318 0.81687465 0.55164845 0.1773866  0.74401521]
 [0.34377166 0.70635333 0.44669473 0.57327704 0.00480679]
 [0.48008666 0.26762535 0.22153895 0.65077559 0.25256537]]


6. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。

In [46]:
import numpy as np
a = np.arange(10)
a[a.max()] *=-1
print(a)

b = np.random.random(10)
b[b.argmax()] = -1
print(b)

[ 0  1  2  3  4  5  6  7  8 -9]
[ 0.75490439  0.7011712   0.50266338  0.59559498  0.24777287 -1.
  0.37941058  0.76556099  0.76282517  0.30242125]


7. 用sort排序

In [15]:
import numpy as np
a = np.array ([1,2,5,8,4])
print(np.sort(a))

[1 2 4 5 8]
