
# D07_NumPy 陣列的索引、切片和迭代

## [Study Summary]

1. 從陣列中存取元素
2. 一維陣列的切片與索引
3. 用「迴圈」的方法，對一維陣列進行迭代
4. 用「迴圈」的方法，對二維陣列進行迭代 適用於 對每個元素作運算
5. 實用的作法，先攤平(flat)，再迭代多維陣列
6. 正確的作法，使用迭代物件(np.nditer)，這樣才可以享有向量運算的特性
7. 迭代物件的儲存方向
   order = 'C': 橫
   order = 'F': 直

## Summary

從陣列中存取元素

In [21]:
import numpy as np
L = [2, 1, 8]

print(L)
print(L[-1])
print(L[0])
print(L[1:3]) #取1 - 2個
print("=================")
a = np.arange(3) * 3

print(a)
print(a[-1]) #倒數第一個
print(a[0]) 
print(a[0:4]) #取0 - 3個

[2, 1, 8]
8
2
[1, 8]
[0 3 6]
6
0
[0 3 6]


一維陣列的切片與索引

In [23]:
import numpy as np 

data = np.array([1, 2, 3, 6, 9, 0])

print(data[0]) # 取出第 0 個
print(data[1]) # 取出第 1 個
print(data[0:2]) # 第 0 - 1 個
print(data[1:]) # 第 1 到最後一個
print(data[-2:]) # 倒數第二到最後一個

1
2
[1 2]
[2 3 6 9 0]
[9 0]


用「迴圈」的方法，對一維陣列進行迭代
適用於 對每個元素作運算

In [7]:
import numpy as np 

a = np.arange(6) + 2 #對每個元素+2
print(a)

for i in a:
    print(i)

[2 3 4 5 6 7]
2
3
4
5
6
7


用「迴圈」的方法，對二維陣列進行迭代 適用於 對每個元素作運算

In [5]:
a = np.arange(12).reshape(4,3) +10

for row in a:
    print(row)

[10 11 12]
[13 14 15]
[16 17 18]
[19 20 21]


實用的作法，先攤平(flat)，再迭代多維陣列

In [9]:
a = np.arange(12).reshape(4,3) + 10

for row in a.flat:
    print(row)

10
11
12
13
14
15
16
17
18
19
20
21


正確的作法，使用迭代物件(np.nditer)，這樣才可以享有向量運算的特性

In [20]:
a = np.arange(4).reshape(2,2)

for row in np.nditer(a):
    print (row)

0
1
2
3


迭代物件的儲存方向
order = 'C': 橫
order = 'F': 直

In [5]:
a = np.arange(12).reshape(4,3)

print(a)
print("========")  

for row in np.nditer(a, order = 'C'):
    print(row)  #3行
    
print("========") 

for row in np.nditer(a, order = 'F'):
    print(row) 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11
0
3
6
9
1
4
7
10
2
5
8
11



## [Homeowork]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。
2. 如何從一個陣列中，找出出現頻率最高的數值與位置？
3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。

## Homework
1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較

In [32]:
import numpy as np

a = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)

In [7]:
#用迴圈
%timeit -n 10 a =2
for row in a:
    for row1 in row:
        row1 = row1 + 1

60 ns ± 16.9 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
#用攤平
%timeit -n 10 a =2
for row in a.flat:
        row = row + 1

47.1 ns ± 10.3 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [14]:
#用迭代
%timeit -n 10 a =2
for row in np.nditer(a):
        row = row + 1  

57.1 ns ± 13.9 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

In [16]:
b = np.random.randint(0,3,5)
b

array([1, 1, 0, 2, 0])

補充randit用法
適用: 隨機產生指定範圍內的整數
公式: np.random.randit(low,high,size)
low: 最低數值
high: 最高數值
size: array大小
ex:np.random.randit(0,5,4) #(0,1,1,4)

In [17]:
binc = (np.bincount(b).argmax()) #最大值
print(binc)
binc = np.argmax(np.bincount(b)) #第二種寫法
print(binc)
binc = (np.bincount(b).argmin()) #最小值
print(binc)
binc = np.where(b == np.max(b))  #最大值的位置，值是2
print(binc)

0
0
2
(array([3], dtype=int64),)


2-1. 如何從二維陣列中，找出出現頻率最高數值的位置？

In [48]:
c = np.random.randint(2,5,10)
print(c)
binc = np.argmax(c)
print(binc)  #最大值3
binc = np.where(c == np.max(c))  #最大值的位置，值是2
print(binc)


[2 2 2 4 4 2 3 2 3 2]
3
(array([3, 4], dtype=int64),)


3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。
   list: 一層的轉換
   tolist: 巢狀的轉換

In [54]:
a = np.random.randint(10, size=(2,3,4)) #多維陣列
print(a)
print("==========")
print(a.tolist())
print("==========")
print(list(a))

[[[0 4 1 1]
  [9 4 7 8]
  [1 1 0 9]]

 [[2 5 5 8]
  [2 6 3 2]
  [9 7 8 8]]]
[[[0, 4, 1, 1], [9, 4, 7, 8], [1, 1, 0, 9]], [[2, 5, 5, 8], [2, 6, 3, 2], [9, 7, 8, 8]]]
[array([[0, 4, 1, 1],
       [9, 4, 7, 8],
       [1, 1, 0, 9]]), array([[2, 5, 5, 8],
       [2, 6, 3, 2],
       [9, 7, 8, 8]])]


In [56]:
a = np.random.randint(10, size=6) #一維陣列
a
print(a.tolist())
print(list(a))

[6, 1, 8, 1, 9, 5]
[6, 1, 8, 1, 9, 5]
